// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/a/:name': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/a/[name]').default>>>>
    }
    '/api/feishu/table': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feishu/table.post').default>>>>
    }
    '/api/hello': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hello.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}